=== Zippo-Wang/terraform-huaweicloud-vpc/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "enterprise_project_id": {
            "type": [
                "string",
                "null"
            ]
        },
        "availability_zone": {
            "type": [
                "string",
                "null"
            ]
        },
        "is_vpc_create": {
            "type": "boolean"
        },
        "vpc_name": {
            "type": [
                "string",
                "null"
            ]
        },
        "vpc_cidr": {
            "type": [
                "string",
                "null"
            ]
        },
        "vpc_description": {
            "type": [
                "string",
                "null"
            ]
        },
        "vpc_secondary_cidrs": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "vpc_tags": {
            "type": "object",
            "properties": {},
            "additionalProperties": {
                "type": "string"
            }
        },
        "subnets_configuration": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "cidr": {
                        "type": "string"
                    },
                    "ipv6_enabled": {
                        "type": "boolean"
                    },
                    "dhcp_enabled": {
                        "type": "boolean"
                    },
                    "dns_list": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "tags": {
                        "type": "object",
                        "properties": {},
                        "additionalProperties": {
                            "type": "string"
                        }
                    },
                    "delete_timeout": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "cidr"
                ]
            }
        },
        "is_security_group_create": {
            "type": "boolean"
        },
        "security_group_name": {
            "type": "string"
        },
        "security_group_description": {
            "type": "string"
        },
        "security_group_rules_configuration": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "direction": {
                        "type": "string"
                    },
                    "ethertype": {
                        "type": "string"
                    },
                    "protocol": {
                        "type": "string"
                    },
                    "ports": {
                        "type": "string"
                    },
                    "remote_ip_prefix": {
                        "type": "string"
                    },
                    "remote_group_id": {
                        "type": "string"
                    },
                    "remote_address_group_id": {
                        "type": "string"
                    },
                    "address_group_name": {
                        "type": "string"
                    },
                    "remote_addresses": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "action": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "integer"
                    }
                }
            }
        },
        "query_vpc_names": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "query_subnet_names": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "query_security_group_names": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false
}

=== Zippo-Wang/terraform-huaweicloud-vpc/examples/full_resource_inputs/variables.json
{
	"enterprise_project_id": "0",
	"vpc_name": "demo",
	"vpc_cidr": "172.16.128.0/20",
	"vpc_description": "Created by terraform module",
	"vpc_secondary_cidrs": ["172.16.192.0/20"],
	"vpc_tags": {
		"foo": "bar"
	},
	"subnets_configuration": [
        {
			"name": "demo-master",
			"description": "Created by terraform module",
			"cidr": "172.16.136.0/24",
			"ipv6_enabled": false,
			"dhcp_enabled": false,
			"dns_list": ["5.5.5.5"],
			"tags": {
				"foo": "bar"
			},
			"delete_timeout": "30m"
		},
		{
			"name": "demo-slave",
			"cidr": "172.16.138.0/24"
		}
	],
	"security_group_name": "demo",
	"security_group_description": "Created by terraform module",
	"security_group_rules_configuration": [
        {
			"description": "Created by terraform module",
			"direction": "ingress",
			"ethertype": "IPv4",
			"protocol": "icmp",
			"priority": 100
		},
		{
			"description": "Created by terraform module",
			"direction": "ingress",
			"ethertype": "IPv6",
			"protocol": "icmp",
			"remote_ip_prefix": "::/0",
			"priority": 100
		},
		{
			"direction": "egress",
			"ethertype": "IPv4",
			"priority": 1
		},
		{
			"direction": "egress",
			"ethertype": "IPv6",
			"remote_ip_prefix": "::/0",
			"priority": 1
		},
		{
			"direction": "ingress",
			"ethertype": "IPv6",
			"protocol": "tcp",
			"ports": "22",
			"address_group_name": "ipv6_address_group",
			"remote_addresses": ["FC00:0:130F:0:0:9C0:876A:130B"],
			"action": "deny",
			"priority": 100
		},
		{
			"protocol": "tcp",
			"ports": "30000",
			"address_group_name": "ipv4_address_group",
			"remote_addresses": ["192.168.128.0", "192.168.128.3-192.168.128.99"],
			"priority": 100
		}
	]
}

=== Zippo-Wang/terraform-huaweicloud-vpc/examples/simple_vpc_subnets/variables.json
{
	"enterprise_project_id": "0",
	"vpc_name": "demo",
	"vpc_cidr": "172.16.128.0/20",
	"vpc_description": "Created by terraform module",
	"vpc_secondary_cidrs": ["172.16.192.0/20"],
	"vpc_tags": {
		"foo": "bar"
	},
	"subnets_configuration": [
        {
			"name": "demo-master",
			"description": "Created by terraform module",
			"cidr": "172.16.136.0/24",
			"ipv6_enabled": false,
			"dhcp_enabled": false,
			"dns_list": ["5.5.5.5"],
			"tags": {
				"foo": "bar"
			},
			"delete_timeout": "30m"
		},
		{
			"name": "demo-slave",
			"cidr": "172.16.138.0/24"
		}
	]
}

=== Zippo-Wang/terraform-huaweicloud-vpc/examples/simple_security_group_rules/variables.json
{
	"enterprise_project_id": "0",
	"security_group_name": "demo",
	"security_group_description": "Created by terraform module",
	"security_group_rules_configuration": [
        {
		    "description": "Created by terraform module",
		    "direction": "ingress",
		    "ethertype": "IPv6",
		    "protocol": "tcp",
		    "ports": "22",
		    "remote_ip_prefix": "::/0",
		    "action": "deny",
		    "priority": 100
		},
		{
			"protocol": "tcp",
			"ports": "30000",
			"priority": 100
		},
		{
			"protocol": "icmp"
		}
	]
}
